/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzycmeans;

import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Fredy Guerrero
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    ArrayList<Dato> arrPuntos = new ArrayList<Dato>();
    ArrayList<Centroide> arrCentroides = new ArrayList<Centroide>();
    
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCargarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fuzzyParamTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numeroClustersTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfNumeroIteraciones = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnSiguienteIteracion = new javax.swing.JButton();
        btnTodasIteraciones = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tfRutaDataSet = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfRutaReporte = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 280));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        btnCargarDatos.setText("Cargar Datos");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Implementación  de Fuzzy C - Means");

        jLabel2.setText("Notas de Matemáticas");

        jLabel3.setText("0                          1                           2                           3                         4                           5");

        jLabel5.setText("5");

        jLabel6.setText("4");

        jLabel7.setText("3");

        jLabel8.setText("2");

        jLabel9.setText("1");

        jLabel10.setText("0");

        jLabel4.setText("Parámero de fuzzyficación :");

        jLabel11.setText("Número de Clusters            :");

        jLabel12.setText("Notas de Sociales");

        tfNumeroIteraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroIteracionesActionPerformed(evt);
            }
        });

        jLabel14.setText("Número de Iteraciones       :");

        btnSiguienteIteracion.setText("Siguiente Iteración");
        btnSiguienteIteracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteIteracionActionPerformed(evt);
            }
        });

        btnTodasIteraciones.setText("Todas Las Iteraciones");
        btnTodasIteraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasIteracionesActionPerformed(evt);
            }
        });

        jLabel15.setText("Ruta del Data Set :");

        jLabel16.setText("Ruta del Reporte  :");

        tfRutaReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRutaReporteActionPerformed(evt);
            }
        });

        jLabel17.setText("Mensajes   :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnSiguienteIteracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTodasIteraciones)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCargarDatos)
                                .addGap(187, 187, 187))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numeroClustersTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fuzzyParamTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNumeroIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRutaDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRutaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel12)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tfRutaDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tfRutaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCargarDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fuzzyParamTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(numeroClustersTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfNumeroIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSiguienteIteracion)
                        .addComponent(btnTodasIteraciones)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        
        
        int numeroClusters = 0;
        float parametroFuzzy = 0;
        int numeroIteraciones = 0;
        String rutaDataSet = "";

        
        Centroide cent = new Centroide();
        FuzzyCMeans fuzzy = new FuzzyCMeans();
        
        try{        
        parametroFuzzy = Float.parseFloat(fuzzyParamTF.getText());// lectura del parámetro de fuzzyficación.
        numeroClusters = Integer.parseInt(numeroClustersTF.getText());// lectura del número de clusters.
        numeroIteraciones = Integer.parseInt(tfNumeroIteraciones.getText()); // lectura del número de iteraciones.
        rutaDataSet = tfRutaDataSet.getText();// lectura de la cadena con la ruta donde se encuentra el data set.
        }catch(Exception e){}
        
        if(parametroFuzzy > 1 && numeroClusters >= 1 && numeroIteraciones > 0){// validación de entradas
            jLabel13.setText("");
            try {
            arrPuntos = fuzzy.leerFicheroMapeoArreglo(rutaDataSet); // cargamos una lista de datos desde un .txt
            jLabel13.setText("Se han Cargado "+arrPuntos.size()+" Registros"); // imprimimos el número de registros cargados.
            arrCentroides = cent.generarCentroidesIniciales(numeroClusters);// generamos el número de centroides especificado con posición inicial aleatoria.
            dibujarPuntos(arrPuntos, arrCentroides);// dibujamos los datos iniciales.
            } catch (IOException ex) {
                jLabel13.setText("No existe el fichero DataSet");// impresión de mensaje de error
            }
        }
        
        else{
            jLabel13.setText("Error en los parámetros de entrada");
        }
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void btnSiguienteIteracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteIteracionActionPerformed
        
        int numeroClusters;
        float parametroFuzzy;
        String rutaReporte;
        
        FuzzyCMeans fuzzy = new FuzzyCMeans();
        
        parametroFuzzy = Float.parseFloat(fuzzyParamTF.getText());
        numeroClusters = Integer.parseInt(numeroClustersTF.getText());
        rutaReporte = tfRutaReporte.getText();
        
        if(parametroFuzzy > 1 && numeroClusters >= 1){

            arrPuntos = fuzzy.asignarDistanciasAlCuadrado(arrCentroides, arrPuntos);// se agregan las distanias de cada dato a cada uno de los clusters 
            arrPuntos = fuzzy.asignarDatosACluster(arrPuntos, numeroClusters, arrCentroides);// se asignan los datos a un cluster 
            arrPuntos = fuzzy.calcularPertenenciaDatos(arrPuntos, parametroFuzzy);// se asigna la pertenencia de ccada dato a todos los clusters
            arrCentroides = fuzzy.calcularCentroides(arrCentroides, arrPuntos, parametroFuzzy);// se Recalcula la posición del centroide de cada grupo de datos.
            try {
                dibujarPuntos(arrPuntos, arrCentroides); // se grafican los datos.
            } catch (IOException ex) {
                jLabel13.setText("No existe el fichero DataSet");
            }
            
            try {
                fuzzy.generarReporte(arrPuntos, arrCentroides, rutaReporte);// se genera el reporte después de cada iteración.
            } catch (IOException ex) {
                jLabel13.setText("No existe la ruta de Reporte");
            }
        }
        else{
            jLabel13.setText("Error en los parámetros de entrada");
        }
    }//GEN-LAST:event_btnSiguienteIteracionActionPerformed

    private void tfNumeroIteracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroIteracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroIteracionesActionPerformed

    private void tfRutaReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRutaReporteActionPerformed
        // TODO add your handling code he
    }//GEN-LAST:event_tfRutaReporteActionPerformed

    private void btnTodasIteracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasIteracionesActionPerformed
        
        int numeroClusters = 0;
        float parametroFuzzy = 0;
        int numeroIteraciones = 0;
        
        String rutaReporte;
        
        FuzzyCMeans fuzzy = new FuzzyCMeans();
        rutaReporte = tfRutaReporte.getText();
        
        parametroFuzzy = Float.parseFloat(fuzzyParamTF.getText());
        numeroClusters = Integer.parseInt(numeroClustersTF.getText());
        numeroIteraciones = Integer.parseInt(tfNumeroIteraciones.getText());
        
        
        for (int i=0; i< numeroIteraciones; i++){// se ejecutn las mismas acciones de siguiente iteración pero tantas veces como se ha especificado en el número de iteraciones.
            try{        
        parametroFuzzy = Float.parseFloat(fuzzyParamTF.getText());
        numeroClusters = Integer.parseInt(numeroClustersTF.getText());
        numeroIteraciones = Integer.parseInt(tfNumeroIteraciones.getText());
        
        }catch(Exception e){}
        if(parametroFuzzy > 1 && numeroClusters >= 1){

            arrPuntos = fuzzy.asignarDistanciasAlCuadrado(arrCentroides, arrPuntos);// se agregan las distanias en arr puntos VERIFICADO
            arrPuntos = fuzzy.asignarDatosACluster(arrPuntos, numeroClusters, arrCentroides);// se asignan los datos a un cluster VERIFICADO
            arrPuntos = fuzzy.calcularPertenenciaDatos(arrPuntos, parametroFuzzy);// se asigna la pertenencia en arr puntos
            arrCentroides = fuzzy.calcularCentroides(arrCentroides, arrPuntos, parametroFuzzy);
            try {
                dibujarPuntos(arrPuntos, arrCentroides);
            } catch (IOException ex) {
                jLabel13.setText("No existe el fichero DataSet");
            }
        }
        else{
            jLabel13.setText("Error en los parámetros de entrada");
        }
        }
            try {
                fuzzy.generarReporte(arrPuntos, arrCentroides, rutaReporte);
            } catch (IOException ex) {
                jLabel13.setText("No existe la ruta de Reporte");
            }
        
    }//GEN-LAST:event_btnTodasIteracionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnSiguienteIteracion;
    private javax.swing.JButton btnTodasIteraciones;
    private javax.swing.JTextField fuzzyParamTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numeroClustersTF;
    private javax.swing.JTextField tfNumeroIteraciones;
    private javax.swing.JTextField tfRutaDataSet;
    private javax.swing.JTextField tfRutaReporte;
    // End of variables declaration//GEN-END:variables


    public void dibujarPuntos(ArrayList<Dato> puntos, ArrayList<Centroide> centroides) throws IOException {       
        
        jPanel1.paint(jPanel1.getGraphics());
        Dibujo2D dibujo = new Dibujo2D();
        float coorx;
        float coory;
        // fijamos los colores que vamos a usar para graficar los puntos en la interfaz  como propiedades del sistema 
        System.setProperty("GRIS CLARO", "0X808080");
        System.setProperty("GRIS", "0XC0C0C0");
        System.setProperty("GRIS OSCURO", "0X404040");
        System.setProperty("NEGRO", "0X000000");
        System.setProperty("ROSADO", "0XFFAFAF");
        System.setProperty("NARANJA", "0XE38C2C");
        System.setProperty("AMARILLO", "0XFFFF00");
        System.setProperty("VERDE", "0X00FF00");
        System.setProperty("AZUL", "0X0000FF");
        System.setProperty("AZUL CLARO", "0X00FFFF");
        System.setProperty("ROJO", "0XFF0000");
        
        for (int i=0; i< puntos.size(); i++){// recorremos el set de datos
            dibujo = new Dibujo2D();
            coorx = (puntos.get(i).getNotaMatematicas())*440; // ajustamos las coordenadas al tamaño del panel de impresión, en este caso de 450x280
            coory = (float) ((1.02 - puntos.get(i).getNotaSociales())*270);// ajustamos en y, invertimos la coordenada en y para que coresponda con el plano cartesiano.
            dibujo.dibujarDato(jPanel1.getGraphics(), (int)coorx, (int)coory, puntos.get(i).getColor());// dibujamos el dato en el panel
    }
        for(int j=0; j<centroides.size(); j++){// hacemos el mismo procedimiento anterior pero para los centroides.
            dibujo = new Dibujo2D();
            coorx = (float)((centroides.get(j).getCoordx())*440);
            coory = (float)((1.02 - centroides.get(j).getCoordy())*270);
            dibujo.dibujarCentroide(jPanel1.getGraphics(), (int)coorx, (int)coory, centroides.get(j).getCol());
        }
    }
}
